apiVersion: v1
kind: Service
metadata:
  name: localops-api
  namespace: {{ .Values.namespace }}
  labels:
    app: localops-api
spec:
  type: ClusterIP
  selector:
    app: localops-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
