apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: localops-api
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - ops-dev
  selector:
    matchLabels:
      app: localops-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
