apiVersion: v1
kind: Service
metadata:
  name: localops-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: localops-frontend
spec:
  type: ClusterIP
  selector:
    app: localops-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
